baseURL = 'https://personal-blog-fzfb.onrender.com'
languageCode = 'en-us'
title = 'Dawn Chan'
theme = 'typo'

[taxanomies]
tag = 'tags'

[params]
description = 'Blog of Dawn Chan'

theme = 'auto'

homeIntroTitle = 'Welcome to my blog!'
homeIntroContent = """
  I am a Chinese college student in Wuhan Univ.
  Intereted in topics of a wide range including FP, PLT, Architecture, UI/UX and a lot more.
  Know something about C#, TypeScript, Haskell, Rust and frameworks related.
"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'

paginationSize = 10
listSummaries = true

breadcrumbs = true

# Social links

[[params.social]]
name = "github"
url = "https://github.com/dawnchan030920"

[[params.social]]
name = "rss"
url = "/index.xml"

# Menus

[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "tags"
url = "/tags"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "about"
url = "/about"

[[params.menu]]
name = "friends"
url = "/friends"

[markup]
[markup.highlight]
style = "onedark"

[params.giscus]
enable = true
repo = "dawnchan030920/blog-comment"
repoId = "R_kgDOMMrO_g"
category = "Announcements"
categoryId = "DIC_kwDOMMrO_s4CgR7i"
mapping = "pathname"
theme = "preferred_color_scheme"

[outputs]
home = ["HTML", "RSS"]

[security]
enableInlineShortcodes = true
